title: "Salman Zahoor Portfolio"
description: "Computer Engineering Student | Pro Portfolio"
url: "https://salmanportfolio.github.io"
baseurl: ""

theme: null  # Using your forked Contrast theme

plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-paginate

markdown: kramdown
permalink: /:title/
show_excerpts: true
dark_mode: true
